// Generated by `deno task gen` from spec/palette.json — do not edit.

export const MotifLight = {
  themeName: "Motif Light",
  palette: {
    primary: { main: "#a60c49" },
    secondary: { main: "#2d6a7a" },
    background: { default: "#fef6e4", paper: "#f3e1d8" },
    text: { primary: "#172c66", secondary: "#45527e" },
    type: "light",
  },
  overrides: {
    NDLogin: { systemNameLink: { color: "#a60c49" } },
  },
  player: { theme: "light" },
};

export const MotifDark = {
  themeName: "Motif Dark",
  palette: {
    primary: { main: "#ff8e8c" },
    secondary: { main: "#abd1c6" },
    background: { default: "#3a2a55", paper: "#4a3a6a" },
    text: { primary: "#e8e2f3", secondary: "#d0c8e8" },
    type: "dark",
  },
  overrides: {
    NDLogin: { systemNameLink: { color: "#ff8e8c" } },
  },
  player: { theme: "dark" },
};
